//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public string AlbumTitle { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Artist { get; set; }
        public Nullable<int> Tracks { get; set; }
        public byte[] Cover { get; set; }
        public string CoverPatch { get; set; }
        public string Description { get; set; }
    }
}
