//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayList
    {
        private int id;
        private int songId;
        private string playListName;
        private string description;

        public PlayList()
        {

        }

        public PlayList(int id, int songId, string playlistName, string description)
        {
            Id = id;
            SongId = songId;
            PlayListName = playlistName;
            Description = description;
        }

        public int Id { get; set; }
        public int SongId { get; set; }
        public string PlayListName { get; set; }
        public string Description { get; set; }
    
        public virtual Song Song { get; set; }
        
    }
}
