//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayList
    {
        private int id;
        private int songId;
        private string playListName;
        private string description;

        public PlayList()
        {

        }

        public PlayList(int id, int songId, string playlistName, string description)
        {
            Id = id;
            SongId = songId;
            PlayListName = playlistName;
            Description = description;
        }

        public int Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }
        public int SongId
        {
            get
            {
                return this.songId;
            }
            set
            {
                this.songId = value;
            }
        }
        public string PlayListName
        {
            get
            {
                return this.playListName;
            }
            set
            {
                if (value.Length <= 50)
                {
                    this.playListName = value;
                }
                else
                {
                    throw new ArgumentOutOfRangeException(value, "Playlist Name must less than 50 character");
                }
                
            }
        }
        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value;
            }
        }
    
        public virtual Song Song { get; set; }
        
    }
}
