//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Song
    {
        private string title;
        private string artistName;
        private int? albumId;
        private int? sequenceId;
        private string description;
        private int? rating;
        private DateTime year;
        private string genre;

        public Song(string title, string artist, int albumId, int sequenceId, string description, string filePath, uint year, string genre, int rating)
        {
            Title = title;
            ArtistName = artist;
            AlbumId = albumId;
            SequenceId = sequenceId;
            Description = description;
            PathToFile = filePath;
            try
            {
                Year = DateTime.ParseExact(year.ToString(), "yyyy", null);
            }
            catch (FormatException ex)
            {
                Console.WriteLine(ex);
                Year = new DateTime(1900, 01, 01);
            }
            Genre = genre;
            Rating = rating;
        }

        [Key]
        public int Id { get; set; }
        public string Title
        {
            get { return title; }
            set { title = value; }
        }
        public string ArtistName
        {
            get { return artistName; }
            set { artistName = value; }
        }
        public Nullable<int> AlbumId
        {
            get { return albumId; }
            set { albumId = value; }
        }
        public Nullable<int> SequenceId
        {
            get { return sequenceId; }
            set { sequenceId = value; }
        }
        public string Description
        {
            get { return description; }
            set { description = value; }
        }
        public string PathToFile
        {
            get { return description; }
            set { description = value; }
        }
        public System.DateTime Year
        {
            get { return year; }
            set { year = value; }
        }
        public string Genre
        {
            get { return genre; }
            set { genre = value; }
        }
        public Nullable<int> Rating
        {
            get { return rating; }
            set { rating = value; }
        }
    }
}
