//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ArtistName { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public string Description { get; set; }
        public string PathToFile { get; set; }
        public System.DateTime Year { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
